# Generated by Django 4.0.5 on 2022-10-08 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='nickname',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
    ]
